# Lista de versões do xk6:
# https://github.com/grafana/xk6/releases

# Extensão para Redis:
# https://github.com/grafana/xk6-redis

trigger:
- main

resources:
  containers:
    - container: redis
      image: redis:alpine
      command: redis-server --requirepass Redis2021!
      networks: 
        - testes
      ports:
        - 6379:6379

variables:
  loadTestsScript: 'loadtests-redis.js'
  testsDirectory: './Tests'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Tests
  displayName: Tests stage
  jobs:
  - job: Tests
    displayName: Tests
    pool:
      vmImage: $(vmImageName)
    services:
      redis: redis
    steps:
    - script: docker container ls
      displayName: Exibir containers em execução
    - script: |
        mkdir $(testsDirectory)
        cd $(testsDirectory)
        wget https://github.com/grafana/xk6/releases/download/v0.5.0/xk6_0.5.0_linux_amd64.tar.gz
        tar -xvf xk6_0.5.0_linux_amd64.tar.gz
      displayName: Baixar e instalar o módulo do k6 para extensões (xk6)
    - script: |
        cd $(testsDirectory)
        ./xk6 build v0.32.0 --with github.com/k6io/xk6-redis
        ./k6
      displayName: Gerar o executável do k6 com suporte ao Redis
    - script: |
        cd $(testsDirectory)
        ./k6 run $(loadTestsScript)
      displayName: Executar testes de carga acessando o Redis